---
- name: Pull docker image of Calculator from dockerhub
  hosts: dev
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: pull docker image
      shell: docker pull deepak18/calculator
      
    - name: running container
      shell: docker run -it -d deepak18/calculator
