---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
  
    - name: Start docker servicee
      service:
        name: docker
        state: started
        
    - name: pull docker image
      shell: docker pull deepak18/calculator
      
    - name: running container
      shell: docker run -it -d --name cal deepak18/calculator
